apiVersion: v1
kind: Service
metadata:
  name: mongo-express-svc
  namespace: mongo
spec:
  type: LoadBalancer
  selector:
    app: mongo-express
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8081