apiVersion: v1 
kind: Pod
metadata:
  name: cm-pod
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    env:
      - name: PORT_NUMBER
        valueFrom:
          configMapKeyRef: 
            name: config-map 
            key: port