apiVersion: apps/v1
kind: Deployment
metadata:
  name: utc-app
  labels:
    app: nginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
      env: dev
  template:
    metadata:
      labels:
        app: nginx
        env: dev
    spec:
      containers:
      - name: nginx
        image: 654654479127.dkr.ecr.us-east-1.amazonaws.com/devops:18
        ports:
        - containerPort: 8082
      tolerations:
        - key: "color"
          operator: "Equal"  # 
          value: "green"
          effect: "NoSchedule"