apiVersion: v1
kind: Service
metadata:
  name: utc-svc
spec:
  type: ExternalName
  externalName: utc-svc.default.svc.cluster.local
  selector:
    app: nginx
    env: dev
  ports:
    - name: utc-svc-port
      protocol: TCP
      port: 80
      targetPort: 8082