apiVersion: v1
kind: Service
metadata:
  name: utc-svc
spec:
  type: NodePort
  selector:
    app: nginx
    env: dev
  ports:
    - name: utc-svc-port
      protocol: TCP
      port: 80
      targetPort: 8082
      nodePort: 30001   # 30000-32767