apiVersion: v1
kind: Service
metadata:
  name: utc-svc
spec:
  type: LoadBalancer
  selector:
    app: nginx
    env: dev
  ports:
    - name: utc-svc-port
      protocol: TCP
      port: 80
      targetPort: 8082