apiVersion: v1
kind: Pod
metadata:
  name: webserver1
#  namespace: dev
spec:
  containers:
    - name: webserver1
      image: httpd
      ports:
        - containerPort: 80
          name: http
          protocol: TCP
  tolerations:
  - key: "color"
    operator: "Equal"  # 
    value: "green"
    effect: "NoSchedule"